Repository econia-labs/emojicoin-dot-fun, pull requests merged in 2024-12, with the labels that each got.

#418 [ECO-1966] Serve fonts and charting library through CDN
  src/typescript/frontend/public/fonts/FormaDJRDisplay-Medium-Testing.woff2
  src/typescript/frontend/public/fonts/FormaDJRDisplay-Regular-Testing.woff2
  src/typescript/frontend/public/fonts/FormaDJRMicro-Regular-Testing.woff2
  src/typescript/frontend/public/fonts/Pixelar-Regular.woff2
  src/typescript/frontend/src/app/layout.tsx
  src/typescript/frontend/src/components/charts/const.ts
  src/typescript/frontend/src/components/error-boundary/ErrorBoundaryFallback.tsx
  src/typescript/frontend/src/lib/env.ts
  src/typescript/frontend/src/styles/fonts.ts
  src/typescript/frontend/tailwind.config.js
Labels: urgency-medium, size-small

#409 [ECO-2493] Change chart to use quote volume, set default visible range
  src/typescript/frontend/src/app/candlesticks/utils.ts
  src/typescript/frontend/src/app/market/[market]/page.tsx
  src/typescript/frontend/src/components/charts/PrivateChart.tsx
  src/typescript/frontend/src/components/charts/const.ts
  src/typescript/frontend/src/lib/store/event/candlestick-bars.ts
  src/typescript/frontend/src/utils/index.ts
Labels: urgency-high, size-small

#431 [ECO-2266] Add go to page button
  src/typescript/frontend/src/components/EmojiPill.tsx
  src/typescript/frontend/src/components/header/wallet-button/ConnectWalletButton.tsx
  src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/table-row/index.tsx
  src/typescript/frontend/src/components/pages/pools/components/liquidity/index.tsx
  src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-header/index.tsx
  src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-row-desktop/XprPopup.tsx
  src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-row-desktop/index.tsx
  src/typescript/frontend/src/components/popup/index.tsx
Labels: urgency-medium, size-medium

#437 [ECO-2473] Use balance before swap to display rank emoji
  src/typescript/frontend/src/lib/utils/get-user-rank.ts
Labels: urgency-medium, size-small

#434 [ECO-2531] Add Bitget to the wallet adapter
  src/typescript/frontend/package.json
  src/typescript/frontend/public/images/wallets/bitget-logo.png
  src/typescript/frontend/public/images/wallets/okx-logo.png
  src/typescript/frontend/src/components/svg/icons/BitgetIcon.tsx
  src/typescript/frontend/src/components/svg/icons/OKXIcon.tsx
  src/typescript/frontend/src/components/wallet/toasts.tsx
  src/typescript/frontend/src/context/providers.tsx
  src/typescript/frontend/src/context/wallet-context/WalletItem.tsx
  src/typescript/frontend/src/middleware.ts
  src/typescript/pnpm-lock.yaml
Labels: urgency-high, size-small

#436 [ECO-2482] Use number wrapper to display numbers
  cfg/cspell-frontend-dictionary.txt
  src/typescript/frontend/src/components/FormattedNumber.tsx
  src/typescript/frontend/src/components/pages/emojicoin/components/main-info/BondingProgress.tsx
  src/typescript/frontend/src/components/pages/emojicoin/components/main-info/MainInfo.tsx
  src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapComponent.tsx
  src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/index.tsx
  src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/table-row/index.tsx
  src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/table-row/types.ts
  src/typescript/frontend/src/components/pages/home/components/emoji-table/utils.ts
  src/typescript/frontend/src/components/pages/home/components/main-card/MainCard.tsx
  src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
  src/typescript/frontend/src/components/pages/home/components/table-card/types.ts
  src/typescript/frontend/src/components/pages/pools/components/liquidity/index.tsx
  src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-row-desktop/XprPopup.tsx
  src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-row-desktop/index.tsx
  src/typescript/frontend/src/components/price-feed/inner.tsx
  src/typescript/frontend/src/lib/utils/decimals.ts
Labels: urgency-medium, size-medium

#427 [ECO-2485] Prepare package for release
  cfg/pre-commit-config.yaml
  src/docker/deployer/Dockerfile
  src/typescript/frontend/tsconfig.json
  src/typescript/sdk/package.json
  src/typescript/sdk/src/utils/test/test-accounts.json
  src/typescript/sdk/src/utils/test/test-accounts.ts
  src/typescript/sdk/tsconfig.json
  src/typescript/turbo.json
Labels: urgency-high, size-small

#448 [ECO-2525] Sort pool page by dpr by default
  src/typescript/frontend/src/components/pages/pools/ClientPoolsPage.tsx
  src/typescript/sdk/src/indexer-v2/queries/index.ts
  src/typescript/sdk/src/indexer-v2/queries/query-params.ts
Labels: urgency-medium, size-small

#440 [ECO-2542] Add market metadata module
  src/move/market_metadata/Move.toml
  src/move/market_metadata/README.md
  src/move/market_metadata/sources/emojicoin_dot_fun_market_metadata.move
  src/typescript/frontend/src/app/dev/metadata/page.tsx
  src/typescript/frontend/src/app/dev/verify_api_keys/page.tsx
  src/typescript/frontend/src/app/dev/verify_status/page.tsx
  src/typescript/frontend/src/components/pages/emojicoin/components/chat/ChatBox.tsx
  src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapButton.tsx
  src/typescript/frontend/src/components/pages/launch-emojicoin/hooks/use-is-market-registered.ts
  src/typescript/frontend/src/components/pages/launch-emojicoin/hooks/use-register-market.ts
  src/typescript/frontend/src/components/pages/metadata/MetadataPage.tsx
  src/typescript/frontend/src/components/pages/pools/components/liquidity/index.tsx
  src/typescript/frontend/src/lib/hooks/queries/use-num-markets.ts
  src/typescript/frontend/src/lib/hooks/queries/use-simulate-provide-liquidity.ts
  src/typescript/frontend/src/lib/hooks/queries/use-simulate-swap.ts
  src/typescript/frontend/src/lib/hooks/queries/use-wallet-balance.ts
  src/typescript/frontend/src/lib/queries/aptos-client/market-view.ts
  src/typescript/frontend/tsconfig.json
  src/typescript/sdk/jest.config.js
  src/typescript/sdk/src/client/emojicoin-client.ts
  src/typescript/sdk/src/emojicoin_dot_fun/contract-apis/aptos-framework.ts
  src/typescript/sdk/src/emojicoin_dot_fun/contract-apis/emojicoin-dot-fun.ts
  src/typescript/sdk/src/emojicoin_dot_fun/contract-apis/index.ts
  src/typescript/sdk/src/emojicoin_dot_fun/contract-apis/market-metadata.ts
  src/typescript/sdk/src/emojicoin_dot_fun/index.ts
  src/typescript/sdk/src/indexer-v2/queries/app/home.ts
  src/typescript/sdk/src/markets/utils.ts
  src/typescript/sdk/tests/e2e/broker/websockets.test.ts
  src/typescript/sdk/tests/e2e/calculate-swap.test.ts
  src/typescript/sdk/tests/e2e/queries/address.test.ts
  src/typescript/sdk/tests/e2e/queries/liquidity-pools.test.ts
  src/typescript/sdk/tests/e2e/queries/market-state.test.ts
  src/typescript/sdk/tests/e2e/queries/num-markets.test.ts
  src/typescript/sdk/tests/e2e/queries/simple.test.ts
  src/typescript/sdk/tests/e2e/queries/sorted/sort-queries.test.ts
  src/typescript/sdk/tests/e2e/queries/volume.test.ts
  src/typescript/sdk/tests/e2e/views.test.ts
  src/typescript/sdk/tsconfig.json
Labels: urgency-medium, size-medium
