Repository econia-labs/emojicoin-dot-fun, pull requests merged in 2024-11, with the labels that each got.

#322 [ECO-2362] Fix flaky playwright tests
  .github/workflows/frontend-tests.yaml
  .gitignore
  src/typescript/frontend/playwright.config.ts
  src/typescript/frontend/tests/e2e/market-order.spec.ts
  src/typescript/frontend/tests/e2e/search.spec.ts
  src/typescript/frontend/tsconfig.json
  src/typescript/package.json
  src/typescript/sdk/src/client/emojicoin-client.ts
  src/typescript/sdk/src/utils/test/docker/docker-test-harness.ts
  src/typescript/turbo.json
Labels: urgency-medium, size-small

#326 [ECO-2369] Remove frontend console errors
  src/typescript/frontend/src/components/charts/PrivateChart.tsx
  src/typescript/frontend/src/components/pages/emoji-picker/EmojiPicker.tsx
Labels: urgency-low, size-small

#332 [ECO-2382] Fix non-breaking chat messages
  src/typescript/frontend/src/components/pages/emojicoin/components/chat/components/message-container/index.tsx
Labels: urgency-medium, size-small

#328 [ECO-2256] Fix line break on market with three emojis
  src/typescript/frontend/src/app/global.css
  src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
  src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-header/index.tsx
  src/typescript/frontend/src/components/selects/dropdown-menu/index.tsx
  src/typescript/frontend/src/components/selects/dropdown-menu/module.css
  src/typescript/frontend/src/components/table/index.tsx
  src/typescript/frontend/src/components/text/index.tsx
  src/typescript/frontend/src/components/text/theme.ts
  src/typescript/frontend/src/components/text/types.ts
  src/typescript/frontend/tailwind.config.js
Labels: urgency-medium, size-small

#327 [ECO-2370] Fix small bugs
  src/typescript/frontend/src/components/pages/home/components/emoji-table/index.tsx
  src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
  src/typescript/frontend/src/lib/queries/sorting/query-params.ts
Labels: urgency-medium, size-small

#317 [ECO-2354] Add slippage and gas on trading page
  src/typescript/frontend/src/app/global.css
  src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapButton.tsx
  src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapComponent.tsx
  src/typescript/frontend/src/components/pages/launch-emojicoin/hooks/use-register-market.ts
  src/typescript/frontend/src/components/selects/dropdown-menu/index.tsx
  src/typescript/frontend/src/components/selects/dropdown-menu/module.css
  src/typescript/frontend/src/components/selects/trade-options/index.tsx
  src/typescript/frontend/src/components/selects/types.ts
  src/typescript/frontend/src/const.ts
  src/typescript/frontend/src/lib/hooks/queries/use-simulate-swap.ts
  src/typescript/frontend/src/utils/slippage.ts
  src/typescript/sdk/src/emojicoin_dot_fun/emojicoin-dot-fun.ts
Labels: urgency-high, size-medium

#336 [ECO-2379] Add log environment variables for PostgREST
  src/docker/compose.yaml
Labels: urgency-high, size-small

#268 [ECO-1955] Update loading animation with hearts
  src/typescript/frontend/src/app/loading/page.tsx
  src/typescript/frontend/src/components/emoji-picker/ColoredBytesIndicator.tsx
  src/typescript/frontend/src/components/loading.tsx
  src/typescript/frontend/src/components/pages/emojicoin/components/desktop-grid/index.tsx
  src/typescript/frontend/src/components/pages/launch-emojicoin/animated-emoji-circle/index.tsx
  src/typescript/frontend/src/components/pages/launch-emojicoin/animated-loading-boxes/index.tsx
  src/typescript/frontend/src/components/pages/launch-emojicoin/memoized-launch/index.tsx
  src/typescript/frontend/src/components/pages/pools/components/liquidity/index.tsx
Labels: urgency-medium, size-medium

#323 [ECO-2363] Fix page number wrong on search
  src/typescript/frontend/src/app/home/HomePage.tsx
  src/typescript/frontend/src/app/home/page.tsx
  src/typescript/frontend/src/components/pages/home/components/emoji-table/components/buttons-block/index.tsx
  src/typescript/frontend/src/components/pages/home/components/emoji-table/components/index.ts
  src/typescript/frontend/src/components/pages/home/components/emoji-table/index.tsx
  src/typescript/sdk/src/indexer-v2/queries/app/home.ts
  src/typescript/sdk/src/indexer-v2/queries/utils.ts
  src/typescript/sdk/src/indexer-v2/types/common.ts
Labels: urgency-medium, size-small

#331 [ECO-2358] Update chart error message
  src/typescript/frontend/src/components/charts/PrivateChart.tsx
Labels: urgency-low, size-medium

#320 [ECO-2360] Add claim link module to rewards package
  src/move/rewards/Move.toml
  src/move/rewards/README.md
  src/move/rewards/sources/emojicoin_dot_fun_claim_link.move
  src/move/rewards/sources/emojicoin_dot_fun_rewards.move
Labels: urgency-medium, size-medium

#348 [ECO-2396] Optimize candlesticks
  src/typescript/frontend/src/app/candlesticks/route.ts
  src/typescript/frontend/src/app/candlesticks/utils.ts
  src/typescript/frontend/src/components/charts/PrivateChart.tsx
  src/typescript/sdk/src/const.ts
  src/typescript/sdk/src/indexer-v2/queries/app/candlesticks.ts
  src/typescript/sdk/src/indexer-v2/queries/app/index.ts
  src/typescript/sdk/src/indexer-v2/queries/app/market.ts
  src/typescript/sdk/src/indexer-v2/queries/utils.ts
  src/typescript/sdk/src/indexer-v2/types/common.ts
Labels: urgency-high, size-medium

#349 [ECO-2388] Resolve promises concurrently
  src/typescript/frontend/src/app/home/page.tsx
  src/typescript/frontend/src/app/market/[market]/page.tsx
  src/typescript/frontend/src/components/pages/emojicoin/components/main-info/BondingProgress.tsx
  src/typescript/frontend/src/components/pages/home/components/table-card/animation-variants/event-variants.ts
Labels: urgency-high, size-small

#359 [ECO-2419] Bump stack image versions
  src/cloud-formation/deploy-indexer-main.yaml
  src/cloud-formation/deploy-indexer-production.yaml
Labels: urgency-high, size-small

#367 [ECO-2427] Cache num of markets query
  src/typescript/frontend/src/app/home/page.tsx
Labels: urgency-high

#374 [ECO-2436] Add Aptos API keys to the `Aptos` client anywhere we use it
  src/docker/compose.yaml
  src/docker/example.local.env
  src/docker/example.testnet.env
  src/docker/frontend/Dockerfile
  src/typescript/frontend/.eslintignore
  src/typescript/frontend/src/app/test/route.ts
  src/typescript/frontend/src/app/verify_api_keys/page.tsx
  src/typescript/frontend/src/components/charts/PrivateChart.tsx
  src/typescript/frontend/src/context/providers.tsx
  src/typescript/frontend/src/lib/env.ts
  src/typescript/frontend/src/lib/server-env.ts
  src/typescript/frontend/src/lib/utils/aptos-client.ts
  src/typescript/package.json
  src/typescript/sdk/src/client/emojicoin-client.ts
  src/typescript/sdk/src/const.ts
  src/typescript/sdk/src/emojicoin_dot_fun/aptos-framework.ts
  src/typescript/sdk/src/emojicoin_dot_fun/emojicoin-dot-fun.ts
  src/typescript/sdk/src/utils/aptos-client.ts
  src/typescript/sdk/tests/e2e/queries/client/submit.test.ts
  src/typescript/turbo.json
Labels: urgency-high

#402 [ECO-2483] Cache VPN queries
  src/typescript/frontend/src/configs/index.ts
  src/typescript/frontend/src/configs/local-storage-keys.ts
  src/typescript/frontend/src/context/language-context/helpers.ts
  src/typescript/frontend/src/context/theme-context/index.tsx
  src/typescript/frontend/src/hooks/use-is-user-geoblocked.ts
  src/typescript/frontend/src/utils/index.ts
Labels: urgency-medium, size-medium
